### ISSUE TITLE
Reimplement the "In Progress" section on the egghead homepage

### ISSUE THREAD

**Issue by MaggieAppleton** [eggheadio/egghead-next#842]
Back in April of 2021 we implemented an "in progress" component that helped learners pick up where they left off.

It showed logged in users the last 3 courses they watched at the top of their home page.

Original pitch: #551 

![image](https://user-images.githubusercontent.com/5599295/130646602-2742f25d-1b64-4ef5-b05b-b0b4e966c16d.png)

When we deployed the component, we found a number of users were experiencing bugs and quickly rolled it back: #558 

The issue related to the `SeriesProgress` value in our GraphQL requests conflicting with progress data coming in from client websites (epic react, testing js): https://github.com/eggheadio/egghead-rails/issues/4476

> If the user has watched any lessons from a WBaaS site (pure react, testing js, epic react etc) this query will break because we are adding the x-site-client header to the graphql request.

> We need to tenant the SeriesProgress model to resolve this. There are 2_551_357 SeriesProgress objects so we have to be careful with this data migration.

@theianjones began working on this with help from @jbranchaud: https://github.com/eggheadio/egghead-rails/pull/4487

It's unclear whether the issue with `SeriesProgress` has been resolved.

Open question: have we fixed the conflicting data between our client websites and egghead? Is it safe to try and reimplement this component?

**Comment by jbranchaud** [comment]
It looks like for the vast majority of Series Progress records, we now have the relevant `site` recorded. If this wasn't working before because we didn't know what records belong with what Site Tenant, then it should now have the data it needs.

Here is a query showing that most `series_progresses` records have a `site` recorded.

![CleanShot 2021-08-24 at 13 26 17@2x](https://user-images.githubusercontent.com/694063/130670362-60574b7c-c30d-43d2-a5a1-2a9bf846db39.png)

**Comment by DrShpongle** [comment]
Is it actual still? cc @laurosilvacom
