### ISSUE TITLE
Enforce types on all tests

### ISSUE THREAD

**Issue by pedroapfilho** [eggheadio/egghead-next#85]
What if we implement `typescript` on all the tests? It would help new developers to know what to do and what to expect from it. It would remove typos on tests too (it really helps).

What do you think?

**Comment by joelhooks** [comment]
Using typescript for tests is absolutely something that we want to do.

**Comment by pedroapfilho** [comment]
Can I open an PR to add the boilerplate to do so? For the `cypress` and `jest`?

**Comment by joelhooks** [comment]
@pedroapfilho we are working on a "cla" or contributors license agreement so that we can facilitate this!

**Comment by pedroapfilho** [comment]
Nice! I would love to help to build the new egghead platform!

**Comment by joelhooks** [comment]
our jest test use typescript already but if you wanted to try a PR with changes for cypress i'd definitely look at it. 

we got a CLA in place 😅

**Comment by pedroapfilho** [comment]
CLA? What is this?

**Comment by joelhooks** [comment]
@pedroapfilho it's a `contributors license agreement` that is required because we are a commercial business and any code committed into this repository requires an agreement that it belongs to the business.

I'm going to close this issue, but if you'd like to submit a PR to demonstrate what you are discussing, we'd be happy to look at it.
